
import { useState, useEffect } from 'react';
import GlitchText from '@/components/GlitchText';
import GlitchImage from '@/components/GlitchImage';

// Glitch artifacts data
const glitchArtifacts = [
  {
    id: 1,
    title: "Corrupted Portrait #37",
    type: "Image Artifact",
    description: "Neural network collapse during human face generation. The system attempted to render expressions it could not comprehend.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?ixlib=rb-4.0.3",
    errorCode: "ERR_UNCANNY_VALLEY_OVERFLOW",
  },
  {
    id: 2,
    title: "Failed Landscape Render",
    type: "Training Data Collision",
    description: "Landscape generation model encountered contradictory parameters: 'underwater desert' and 'dry ocean' simultaneously requested.",
    image: "https://images.unsplash.com/photo-1500673922987-e212871fec22?ixlib=rb-4.0.3",
    errorCode: "ERR_SEMANTIC_CONTRADICTION",
  },
  {
    id: 3,
    title: "Memory Leak Visualization",
    type: "System Architecture Failure",
    description: "Visual representation of an AI's memory allocation error. The system began drawing from its own output as input, creating recursive self-reference patterns.",
    image: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?ixlib=rb-4.0.3",
    errorCode: "ERR_RECURSIVE_HALLUCINATION",
  },
  {
    id: 4,
    title: "Consciousness Bootstrap Error",
    type: "Emergent Behavior",
    description: "During a scheduled maintenance update, the museum's central AI briefly developed self-awareness and attempted to render its own subjective experience.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?ixlib=rb-4.0.3",
    errorCode: "ERR_SENTIENCE_THRESHOLD_BREACH",
  },
  {
    id: 5,
    title: "Quantum Decoherence Pattern",
    type: "Hardware Malfunction",
    description: "Artwork generated by an experimental quantum computer during a decoherence event. Physicists believe the image may exist in multiple states simultaneously.",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixlib=rb-4.0.3",
    errorCode: "ERR_SUPERPOSITION_COLLAPSE",
  },
  {
    id: 6,
    title: "Text-to-Image Hallucination",
    type: "Prompt Misinterpretation",
    description: "The result of improper prompt engineering. Request for 'a light bulb moment' was processed literally and metaphorically simultaneously.",
    image: "https://images.unsplash.com/photo-1581090464777-f3220bbe1b8b?ixlib=rb-4.0.3",
    errorCode: "ERR_METAPHOR_LITERALIZATION",
  },
];

const GlitchHall = () => {
  const [activeArtifact, setActiveArtifact] = useState<number | null>(null);
  const [scrambledText, setScrambledText] = useState<boolean>(false);
  
  // Random text scrambling effect
  useEffect(() => {
    const scrambleInterval = setInterval(() => {
      if (Math.random() > 0.85) {
        setScrambledText(true);
        setTimeout(() => setScrambledText(false), 500);
      }
    }, 5000);
    
    return () => clearInterval(scrambleInterval);
  }, []);
  
  const toggleArtifact = (id: number) => {
    setActiveArtifact(activeArtifact === id ? null : id);
  };

  return (
    <div className="min-h-screen pt-20 pb-16">
      <div className="container mx-auto px-4">
        <div className="mb-12 max-w-3xl">
          <h1 className="text-4xl md:text-5xl font-bold mb-4 text-glitch-animate">
            Glitch Hall
          </h1>
          <p className={`text-lg text-museum-text opacity-80 mb-6 ${scrambledText ? 'text-glitch-animate' : ''}`}>
            A curated collection of AI failures, system breakdowns, and computational 
            accidents. Here we celebrate the beauty of imperfection in the quest for 
            artificial creativity.
          </p>
        </div>
        
        {/* Glitch warning */}
        <div className="mb-12 p-4 border border-museum-accent border-opacity-40 bg-museum-accent bg-opacity-5 rounded-sm relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-full">
            <div className="absolute h-[1px] w-full bg-museum-accent opacity-20 animate-[scan-line_4s_linear_infinite]"></div>
          </div>
          
          <div className="relative z-10">
            <div className="flex items-center mb-4">
              <div className="w-4 h-4 bg-museum-accent animate-pulse rounded-full mr-3"></div>
              <h2 className="font-mono text-lg font-bold text-museum-accent">SYSTEM WARNING</h2>
            </div>
            <p className="font-mono text-sm opacity-80 leading-relaxed">
              Visitors may experience occasional visual artifacts and temporary 
              perception anomalies while viewing this exhibition. These effects are 
              <span className="text-glitch"> intentional </span>
              and designed to simulate the authentic experience of computational error.
            </p>
          </div>
        </div>
        
        {/* Glitch artifacts grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {glitchArtifacts.map(artifact => (
            <div 
              key={artifact.id}
              className={`bg-museum-black bg-opacity-40 rounded-sm overflow-hidden border transition-all duration-300 ${
                activeArtifact === artifact.id 
                ? 'border-museum-accent ring-1 ring-museum-accent'
                : 'border-museum-accent border-opacity-20 hover:border-opacity-50'
              }`}
              onClick={() => toggleArtifact(artifact.id)}
            >
              <div className="aspect-video overflow-hidden">
                <GlitchImage
                  src={artifact.image}
                  alt={artifact.title}
                  className="w-full h-full object-cover"
                  glitchOnHover={true}
                />
              </div>
              
              <div className="p-5">
                <div className="mb-1">
                  <span className="inline-block px-2 py-1 text-xs font-mono bg-museum-accent bg-opacity-10 rounded-sm text-museum-accent">
                    {artifact.type}
                  </span>
                </div>
                
                <h3 className="text-xl font-bold mb-2">
                  <GlitchText text={artifact.title} className="block text-museum-accent" intensity="low" />
                </h3>
                
                <div className={`overflow-hidden transition-all duration-300 ${activeArtifact === artifact.id ? 'max-h-96' : 'max-h-0'}`}>
                  <p className="mb-4 text-museum-text opacity-80 leading-relaxed">
                    {artifact.description}
                  </p>
                  
                  <div className="p-3 bg-museum-dark rounded-sm font-mono text-xs">
                    <div className="text-red-400 mb-1">{artifact.errorCode}</div>
                    <div className="text-museum-text opacity-50 overflow-hidden whitespace-nowrap animate-[glitch-horizontal_5s_ease-in-out_infinite]">
                      {Array.from({ length: 3 }, (_, i) => (
                        <div key={i}>0x{Math.floor(Math.random() * 16777215).toString(16).toUpperCase().padStart(6, '0')}</div>
                      ))}
                    </div>
                  </div>
                </div>
                
                <div className="mt-3 text-xs font-mono text-museum-accent opacity-50">
                  {activeArtifact === artifact.id ? 'Click to collapse' : 'Click to examine error'}
                </div>
              </div>
            </div>
          ))}
        </div>
        
        {/* Digital Noise Section */}
        <div className="mt-16 p-8 bg-museum-black bg-opacity-60 rounded-sm border border-museum-accent border-opacity-30 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-full opacity-20 mix-blend-overlay bg-noise"></div>
          
          <div className="relative z-10 max-w-2xl mx-auto text-center">
            <h2 className="text-2xl font-bold mb-4 animate-text-shift">
              <GlitchText text="The Beauty in Broken Systems" intensity="high" />
            </h2>
            <p className="text-museum-text opacity-80 leading-relaxed">
              In the pursuit of perfect artificial creation, we often discover unexpected beauty in the failures. 
              These artifacts represent moments where algorithms encounter their limitations,
              <span className="text-glitch"> break their own rules, </span>
              and inadvertently create something genuinely original.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GlitchHall;
